### ISSUE TITLE
Adding new tasks

### ISSUE THREAD

**Issue by karycio** [kleder/timetracker#23]
As a user I want to add new task to the board I chosen to work with.

**Comment by rkorszun** [comment]
we may use this scenario on our site to make this task done 
![image](https://user-images.githubusercontent.com/8030590/35551834-4850607c-0591-11e8-90a2-4023ffab37c2.png)

**Comment by rkorszun** [comment]
we may also create issue direct in app using the PUT /rest/issue?{project}&{summary}&{description}&{attachments}&{permittedGroup} 
and after taht we need to apply command to move task to current sprint on board
https://www.jetbrains.com/help/youtrack/incloud/Apply-Command-to-an-Issue.html

**Comment by rkorszun** [comment]
@karycio we need only new view and this will be done

**Comment by rkorszun** [comment]
it is done on develop
