### ISSUE TITLE
Records history

### ISSUE THREAD

**Issue by karycio** [kleder/timetracker#30]
As a user I want to see records history from previuos days. 
User should be able to preview records from the last few days with a possibility to show more.   
User should be able to clear the record history whitin the app. This should happen after clicking a button and confirming.

**Comment by rkorszun** [comment]
we should sync work items from YT

**Comment by kamdobrz** [comment]
added in #236cc34adc679ce5f211d017971ea2054e513b0a

**Comment by kamdobrz** [comment]
It is done in 65268bd2ef2dd73b681ddc3dc522d28e39698213. At this moment clearing history is not needed.
