### ISSUE TITLE
Ubuntu LTS deb packages

### ISSUE THREAD

**Issue by k0sci3j** [kleder/timetracker#31]
## Expected Behavior
There should be available deb package for Ubuntu. As this is one of the most popular distributions in the world (https://distrowatch.com/dwres.php?resource=popularity).

## Actual Behavior
There is old tar.gz package

## Steps to Reproduce the Problem

Not applicable

## Specifications

  - T-REC Version: all
  - Platform: (mac/linux/windows): Linux

**Comment by rkorszun** [comment]
Thanks @binowl for contribution on current release we start publishing  the deb package
