### ISSUE TITLE
Choose tasks from past and future sprints

### ISSUE THREAD

**Issue by michalkurpis** [kleder/timetracker#36]
## Expected Behavior
User should have possibility to display and report time to tasks from past and future sprints

## Actual Behavior
Only tasks from current sprint are displayed

## Steps to Reproduce the Problem
.

## Specifications

  - T-REC Version: 1.1.0
  - Platform: (mac/linux/windows): all

**Comment by rkorszun** [comment]
I don't think this is good, we should do this more generic: allow to own search query

**Comment by rkorszun** [comment]
this is releated to #40
