### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by pesoshin** [kleder/timetracker#51]
## Expected Behavior

No 404 error in Network tab

## Actual Behavior

404 error in Network tab
![image](https://user-images.githubusercontent.com/148180/48899005-5fb80780-ee5f-11e8-9b7d-521fe5de9398.png)

## Steps to Reproduce the Problem

  1. download app
  1. add new account:
- hightech
- https://hightech.myjetbrains.com/youtrack
- <my perm token>
  1. Stuck in a state "Select agile boards" with infinite spinner 

## Specifications

  - T-REC Version: 1.2.0
  - Platform: mac

**Comment by pesoshin** [comment]
anybody here?

**Comment by nickaguilarh** [comment]
Hey @andreypesoshin 
I got the same problem and solved updating the endpoint used to get all agiles board.
I made a fork. You can check it there. https://github.com/nickaguilarh/timetracker/commit/60fe9d62935480d0dc919493be11450fb43daee6
Idk if this project is still alive.

**Comment by fantomas** [comment]
@nickaguilarh would you like to make a PR?
@rkorszun would you accept it as it is vital for T-Rec to work with the new endpoint of youtrack?

Thanks for the tool! The only one I found to sync back time records to youtrack.

**Comment by nickaguilarh** [comment]
I've just made the pull request. Let me know if anything is needed.
